import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js Tailwind Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline text-red-600">
        Hello worlds!
      </h1>
    </div>
  );
}
